### ISSUE TITLE
Error response from daemon: Cannot start container

### ISSUE THREAD

**Issue by mheuer-nmdp** [nmdp-bioinformatics/flow#20]
```
Apr-30 10:46:11.162 [Thread-4] ERROR nextflow.processor.TaskProcessor - Error executing process > 'reformat (67)'

Caused by:
  Process 'reformat (67)' terminated with an error exit status

Command executed:

  zcat 1367-0038-2_S72_L001.ssake.fa.gz | sed -e 's/a/A/g' -e 's/c/C/g' -e 's/g/G/g' -e 's/t/T/g' -e 's/n/N/g' -e 's/^>.*/>reformatted:500/' | gzip -c > 1367-0038-2_S72_
L001.ssake.reformatted.fa.gz

Command exit status:
  1

Command output:
  (empty)

Command error:
  time="2015-04-30T10:46:10-05:00" level=fatal msg="Error response from daemon: Cannot start container 806b3ae4ccd69b92eb7d23d13099e43b217f1bc1c02cbd977ed5e8322c71cfaf: 
Error getting container 806b3ae4ccd69b92eb7d23d13099e43b217f1bc1c02cbd977ed5e8322c71cfaf from driver devicemapper: Error mounting '/dev/mapper/docker-202:1-666771-806b3a
e4ccd69b92eb7d23d13099e43b217f1bc1c02cbd977ed5e8322c71cfaf' on '/var/lib/docker/devicemapper/mnt/806b3ae4ccd69b92eb7d23d13099e43b217f1bc1c02cbd977ed5e8322c71cfaf': no su
ch file or directory" 

Work dir:
  /mnt/nextflow/work/8c/3a1f113d3efbe87dd91e6d55108052

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named: '.command.sh'
nextflow.exception.ProcessFailedException: Process 'reformat (67)' terminated with an error exit status
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.7.0_79]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[na:1.7.0_79]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.7.0_79]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[na:1.7.0_79]
```

**Comment by mheuer-nmdp** [comment]
Fixed by re-installing docker on worker nodes.
